language: bash

services:
 - docker

before_install:
  - docker pull diegobernardes/flare:0.3

stages:
  - compile
  - quality

jobs:
  include:
    - stage: compile
      script: ./task flare-build

    - stage: quality
      script: ./task lint-fast

    - script: ./task lint-slow

    - script: ./task test

    - script: ./task coveralls

