language: bash

services:
 - docker

before_install:
  - docker pull diegobernardes/flare:0.1

stages:
  - compile
  - quality

jobs:
  include:
    - stage: quality
      script: make lint-fast

    - script: make lint-slow

    - script: make test

    - stage: compile
      script: make flare-build